version: '3.1' #  选择 docker-compose 项目版本号
services:
  client-nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    # image: nginx # 镜像名称
    container_name: nginx # 容器名字
    restart: always # 开机自动重启
    ports:
      - '8080:80'
    networks:
      #当前服务器使用哪个桥
      - app
        # - ./nginx/nginx.conf:/etc/nginx/nginx.conf #配置文件
        # - ./log:/var/log/nginx  ###这里面放置日志
        # - ./html:/html         ###这里面放置项目目录

networks:
  app:
    #声明定义上面的网桥模式 默认创建的是bridge
    # vloumes:
    #     client_nginx_web:

    # mysql:
    #     image: "mysql:5.7"
    #     container_name: mysql
    #     restart: always           	# docker启动，当前容器必启动
    #     ports:
    #         - "3306:3306"
    #     environment:

    #         MYSQL_USER: 'root'
    #         MYSQL_PASS: 'root'
    #         MYSQL_ROOT_PASSWORD: "root"
    #     volumes:
    #         - "./data:/var/lib/mysql"  # 映射多个数据卷 类似于docker run -v 注意：docker-compose使用绝对路劲要求必须先创建才能使用
